language: swift
osx_image: xcode11.6

addons:
  homebrew:
    brewfile: true

cache:
  bundler: true

script:
- set -o pipefail
- swift --version
- rake
- bundle exec fastlane mac validate_pr
- bundle exec pod lib lint
- bundle exec danger